### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by benji877** [gallowayk/FanControlForBentoBox#1]
What sort of ETA could I hope for to see a wiring diagram? Anything loosely pointing me in the correct direction would be stellar. Thanks.

**Comment by gallowayk** [comment]
Hi Benji, I'll get one drafted over the next few days. Expect it by middle of next week. Thanks!

**Comment by iruYo** [comment]
> Hi Benji, I'll get one drafted over the next few days. Expect it by middle of next week. Thanks!

Hey gallowayk! Any news on this? I'd love to try this out

**Comment by younggulch** [comment]
I would also love to try this out! Looking forward to the wiring diagram!

**Comment by gallowayk** [comment]
Hi all, deepest apologies for the delay. I've been a bit swamped after starting a new job. If you don't want to wait, I would suggest reading through the Python code and reviewing the Rpi Pico pin definitions at the top. I used all common grounds and separated +5V and +24V. 

I'm also working on two additional versions of this. One will use a 120mm blower fan and two VOC sensors + the OLED readout. The other will be a lite version that omits the Rpi and OLED, purely running off the calibrated digital output of the VOC sensors.

**Comment by gallowayk** [comment]
Wiring diagram included in images. Closing issue.
